package com.ymsino.water.service.manager.chargingUnit;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * ChargingUnitServiceService service = new ChargingUnitServiceService();
 * ChargingUnitService portType = service.getChargingUnitServicePort();
 * portType.getByUnitId(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "ChargingUnitServiceService", targetNamespace = "http://api.service.manager.esb.ymsino.com/", wsdlLocation = "http://127.0.0.1:8882/ws/chargingUnitService?wsdl")
public class ChargingUnitServiceService extends Service {

	private final static URL CHARGINGUNITSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.ymsino.water.service.manager.chargingUnit.ChargingUnitServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ymsino.water.service.manager.chargingUnit.ChargingUnitServiceService.class.getResource(".");
			url = new URL(baseUrl, "http://127.0.0.1:8882/ws/chargingUnitService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8882/ws/chargingUnitService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		CHARGINGUNITSERVICESERVICE_WSDL_LOCATION = url;
	}

	public ChargingUnitServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ChargingUnitServiceService() {
		super(CHARGINGUNITSERVICESERVICE_WSDL_LOCATION, new QName("http://api.service.manager.esb.ymsino.com/", "ChargingUnitServiceService"));
	}

	/**
	 * 
	 * @return returns ChargingUnitService
	 */
	@WebEndpoint(name = "ChargingUnitServicePort")
	public ChargingUnitService getChargingUnitServicePort() {
		return super.getPort(new QName("http://api.service.manager.esb.ymsino.com/", "ChargingUnitServicePort"), ChargingUnitService.class);
	}

}
