package com.ymsino.water.service.archives.waterMeter;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * WaterMeterServiceService service = new WaterMeterServiceService();
 * WaterMeterService portType = service.getWaterMeterServicePort();
 * portType.save(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "WaterMeterServiceService", targetNamespace = "http://api.service.archives.esb.ymsino.com/", wsdlLocation = "http://127.0.0.1:8882/ws/waterMeterService?wsdl")
public class WaterMeterServiceService extends Service {

	private final static URL WATERMETERSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.ymsino.water.service.archives.waterMeter.WaterMeterServiceService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ymsino.water.service.archives.waterMeter.WaterMeterServiceService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://127.0.0.1:8882/ws/waterMeterService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8882/ws/waterMeterService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		WATERMETERSERVICESERVICE_WSDL_LOCATION = url;
	}

	public WaterMeterServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public WaterMeterServiceService() {
		super(WATERMETERSERVICESERVICE_WSDL_LOCATION, new QName(
				"http://api.service.archives.esb.ymsino.com/",
				"WaterMeterServiceService"));
	}

	/**
	 * 
	 * @return returns WaterMeterService
	 */
	@WebEndpoint(name = "WaterMeterServicePort")
	public WaterMeterService getWaterMeterServicePort() {
		return super.getPort(new QName(
				"http://api.service.archives.esb.ymsino.com/",
				"WaterMeterServicePort"), WaterMeterService.class);
	}

}
