package com.ymsino.water.service.archives.bank;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * BankServiceService service = new BankServiceService();
 * BankService portType = service.getBankServicePort();
 * portType.save(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "BankServiceService", targetNamespace = "http://api.service.archives.esb.ymsino.com/", wsdlLocation = "http://127.0.0.1:8882/ws/bankService?wsdl")
public class BankServiceService extends Service {

	private final static URL BANKSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.ymsino.water.service.archives.bank.BankServiceService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ymsino.water.service.archives.bank.BankServiceService.class
					.getResource(".");
			url = new URL(baseUrl, "http://127.0.0.1:8882/ws/bankService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8882/ws/bankService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		BANKSERVICESERVICE_WSDL_LOCATION = url;
	}

	public BankServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public BankServiceService() {
		super(BANKSERVICESERVICE_WSDL_LOCATION, new QName(
				"http://api.service.archives.esb.ymsino.com/",
				"BankServiceService"));
	}

	/**
	 * 
	 * @return returns BankService
	 */
	@WebEndpoint(name = "BankServicePort")
	public BankService getBankServicePort() {
		return super.getPort(new QName(
				"http://api.service.archives.esb.ymsino.com/",
				"BankServicePort"), BankService.class);
	}

}
