package com.ymsino.water.service.comm.conDebug;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * 
 */
@WebService(name = "ConDebugService", targetNamespace = "http://api.service.comm.esb.ymsino.com/")
public interface ConDebugService {

	/**
	 * 集中器调试
	 * 
	 * @param waterMeterId
	 * @param concHardwareId
	 * @param waterMeterSn
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "debug", targetNamespace = "http://api.service.comm.esb.ymsino.com/", className = "com.ymsino.water.service.comm.conDebug.Debug")
	@ResponseWrapper(localName = "debugResponse", targetNamespace = "http://api.service.comm.esb.ymsino.com/", className = "com.ymsino.water.service.comm.conDebug.DebugResponse")
	public String debug(@WebParam(name = "concHardwareId", targetNamespace = "") String concHardwareId, @WebParam(name = "waterMeterId", targetNamespace = "") String waterMeterId, @WebParam(name = "waterMeterSn", targetNamespace = "") Integer waterMeterSn);

}
