package com.ymsino.water.service.data.checkingFreezeData;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * 
 */
@WebService(name = "CheckingFreezeDataService", targetNamespace = "http://api.service.data.esb.ymsino.com/")
public interface CheckingFreezeDataService {

	/**
	 * 根据查询参数获取水表冻结审核数据分页列表
	 * 
	 * @param queryParam
	 * @param startRow
	 * @param pageSize
	 * @return returns java.util.List<com.ymsino.water.service.data.checkingFreezeData.CheckingFreezeDataReturn>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getListpager", targetNamespace = "http://api.service.data.esb.ymsino.com/", className = "com.ymsino.water.service.data.checkingFreezeData.GetListpager")
	@ResponseWrapper(localName = "getListpagerResponse", targetNamespace = "http://api.service.data.esb.ymsino.com/", className = "com.ymsino.water.service.data.checkingFreezeData.GetListpagerResponse")
	public List<CheckingFreezeDataReturn> getListpager(@WebParam(name = "queryParam", targetNamespace = "") QueryParam queryParam, @WebParam(name = "startRow", targetNamespace = "") Integer startRow, @WebParam(name = "pageSize", targetNamespace = "") Integer pageSize);

	/**
	 * 修改水表冻结审核数据
	 * 
	 * @param checkingFreezeDataModifyParam
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "modify", targetNamespace = "http://api.service.data.esb.ymsino.com/", className = "com.ymsino.water.service.data.checkingFreezeData.Modify")
	@ResponseWrapper(localName = "modifyResponse", targetNamespace = "http://api.service.data.esb.ymsino.com/", className = "com.ymsino.water.service.data.checkingFreezeData.ModifyResponse")
	public Boolean modify(@WebParam(name = "checkingFreezeDataModifyParam", targetNamespace = "") CheckingFreezeDataModifyParam checkingFreezeDataModifyParam);

	/**
	 * 根据查询参数获取水表冻结审核数据总记录数
	 * 
	 * @param queryParam
	 * @return returns java.lang.Integer
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getCount", targetNamespace = "http://api.service.data.esb.ymsino.com/", className = "com.ymsino.water.service.data.checkingFreezeData.GetCount")
	@ResponseWrapper(localName = "getCountResponse", targetNamespace = "http://api.service.data.esb.ymsino.com/", className = "com.ymsino.water.service.data.checkingFreezeData.GetCountResponse")
	public Integer getCount(@WebParam(name = "queryParam", targetNamespace = "") QueryParam queryParam);

	/**
	 * 根据id获取水表冻结审核数据
	 * 
	 * @param id
	 * @return returns com.ymsino.water.service.data.checkingFreezeData.CheckingFreezeDataReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getById", targetNamespace = "http://api.service.data.esb.ymsino.com/", className = "com.ymsino.water.service.data.checkingFreezeData.GetById")
	@ResponseWrapper(localName = "getByIdResponse", targetNamespace = "http://api.service.data.esb.ymsino.com/", className = "com.ymsino.water.service.data.checkingFreezeData.GetByIdResponse")
	public CheckingFreezeDataReturn getById(@WebParam(name = "id", targetNamespace = "") Long id);

}
