package com.ymsino.water.service.data.checkingFreezeData;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * CheckingFreezeDataServiceService service = new CheckingFreezeDataServiceService();
 * CheckingFreezeDataService portType = service.getCheckingFreezeDataServicePort();
 * portType.getListpager(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "CheckingFreezeDataServiceService", targetNamespace = "http://api.service.data.esb.ymsino.com/", wsdlLocation = "http://127.0.0.1:8882/ws/checkingFreezeDataService?wsdl")
public class CheckingFreezeDataServiceService extends Service {

	private final static URL CHECKINGFREEZEDATASERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.ymsino.water.service.data.checkingFreezeData.CheckingFreezeDataServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ymsino.water.service.data.checkingFreezeData.CheckingFreezeDataServiceService.class.getResource(".");
			url = new URL(baseUrl, "http://127.0.0.1:8882/ws/checkingFreezeDataService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8882/ws/checkingFreezeDataService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		CHECKINGFREEZEDATASERVICESERVICE_WSDL_LOCATION = url;
	}

	public CheckingFreezeDataServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public CheckingFreezeDataServiceService() {
		super(CHECKINGFREEZEDATASERVICESERVICE_WSDL_LOCATION, new QName("http://api.service.data.esb.ymsino.com/", "CheckingFreezeDataServiceService"));
	}

	/**
	 * 
	 * @return returns CheckingFreezeDataService
	 */
	@WebEndpoint(name = "CheckingFreezeDataServicePort")
	public CheckingFreezeDataService getCheckingFreezeDataServicePort() {
		return super.getPort(new QName("http://api.service.data.esb.ymsino.com/", "CheckingFreezeDataServicePort"), CheckingFreezeDataService.class);
	}

}
