package com.ymsino.water.service.data.collectTask;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * 
 */
@WebService(name = "CollectTaskService", targetNamespace = "http://api.service.data.esb.ymsino.com/")
public interface CollectTaskService {

	/**
	 * 根据查询参数获取采集任务分页列表
	 * 
	 * @param queryParam
	 * @param startRow
	 * @param pageSize
	 * @return returns java.util.List<com.ymsino.water.service.data.collectTask.CollectTaskReturn>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getListpager", targetNamespace = "http://api.service.data.esb.ymsino.com/", className = "com.ymsino.water.service.data.collectTask.GetListpager")
	@ResponseWrapper(localName = "getListpagerResponse", targetNamespace = "http://api.service.data.esb.ymsino.com/", className = "com.ymsino.water.service.data.collectTask.GetListpagerResponse")
	public List<CollectTaskReturn> getListpager(@WebParam(name = "queryParam", targetNamespace = "") QueryParam queryParam, @WebParam(name = "startRow", targetNamespace = "") Integer startRow, @WebParam(name = "pageSize", targetNamespace = "") Integer pageSize);

	/**
	 * 修改采集任务
	 * 
	 * @param collectTaskModifyParam
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "modify", targetNamespace = "http://api.service.data.esb.ymsino.com/", className = "com.ymsino.water.service.data.collectTask.Modify")
	@ResponseWrapper(localName = "modifyResponse", targetNamespace = "http://api.service.data.esb.ymsino.com/", className = "com.ymsino.water.service.data.collectTask.ModifyResponse")
	public Boolean modify(@WebParam(name = "collectTaskModifyParam", targetNamespace = "") CollectTaskModifyParam collectTaskModifyParam);

	/**
	 * 根据查询参数获取采集任务总记录数
	 * 
	 * @param queryParam
	 * @return returns java.lang.Integer
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getCount", targetNamespace = "http://api.service.data.esb.ymsino.com/", className = "com.ymsino.water.service.data.collectTask.GetCount")
	@ResponseWrapper(localName = "getCountResponse", targetNamespace = "http://api.service.data.esb.ymsino.com/", className = "com.ymsino.water.service.data.collectTask.GetCountResponse")
	public Integer getCount(@WebParam(name = "queryParam", targetNamespace = "") QueryParam queryParam);

	/**
	 * 保存采集任务
	 * 
	 * @param collectTaskSaveParam
	 * @return returns java.lang.Long
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "save", targetNamespace = "http://api.service.data.esb.ymsino.com/", className = "com.ymsino.water.service.data.collectTask.Save")
	@ResponseWrapper(localName = "saveResponse", targetNamespace = "http://api.service.data.esb.ymsino.com/", className = "com.ymsino.water.service.data.collectTask.SaveResponse")
	public Long save(@WebParam(name = "collectTaskSaveParam", targetNamespace = "") CollectTaskSaveParam collectTaskSaveParam);

	/**
	 * 根据id获取采集任务
	 * 
	 * @param id
	 * @return returns com.ymsino.water.service.data.collectTask.CollectTaskReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getById", targetNamespace = "http://api.service.data.esb.ymsino.com/", className = "com.ymsino.water.service.data.collectTask.GetById")
	@ResponseWrapper(localName = "getByIdResponse", targetNamespace = "http://api.service.data.esb.ymsino.com/", className = "com.ymsino.water.service.data.collectTask.GetByIdResponse")
	public CollectTaskReturn getById(@WebParam(name = "id", targetNamespace = "") Long id);

}
