package com.ymsino.water.service.comm.restoreSetting;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * 
 */
@WebService(name = "RestoreSettingService", targetNamespace = "http://api.service.comm.esb.ymsino.com/")
public interface RestoreSettingService {

	/**
	 * 远程复位集中器
	 * 
	 * @param concHardwareId
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "restoreSettings", targetNamespace = "http://api.service.comm.esb.ymsino.com/", className = "com.ymsino.water.service.comm.restoreSetting.RestoreSettings")
	@ResponseWrapper(localName = "restoreSettingsResponse", targetNamespace = "http://api.service.comm.esb.ymsino.com/", className = "com.ymsino.water.service.comm.restoreSetting.RestoreSettingsResponse")
	public String restoreSettings(@WebParam(name = "concHardwareId", targetNamespace = "") String concHardwareId);

}
