package com.ymsino.water.service.comm.restoreSetting;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * RestoreSettingServiceService service = new RestoreSettingServiceService();
 * RestoreSettingService portType = service.getRestoreSettingServicePort();
 * portType.restoreSettings(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "RestoreSettingServiceService", targetNamespace = "http://api.service.comm.esb.ymsino.com/", wsdlLocation = "http://127.0.0.1:8882/ws/restoreSettingService?wsdl")
public class RestoreSettingServiceService extends Service {

	private final static URL RESTORESETTINGSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.ymsino.water.service.comm.restoreSetting.RestoreSettingServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ymsino.water.service.comm.restoreSetting.RestoreSettingServiceService.class.getResource(".");
			url = new URL(baseUrl, "http://127.0.0.1:8882/ws/restoreSettingService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8882/ws/restoreSettingService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		RESTORESETTINGSERVICESERVICE_WSDL_LOCATION = url;
	}

	public RestoreSettingServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public RestoreSettingServiceService() {
		super(RESTORESETTINGSERVICESERVICE_WSDL_LOCATION, new QName("http://api.service.comm.esb.ymsino.com/", "RestoreSettingServiceService"));
	}

	/**
	 * 
	 * @return returns RestoreSettingService
	 */
	@WebEndpoint(name = "RestoreSettingServicePort")
	public RestoreSettingService getRestoreSettingServicePort() {
		return super.getPort(new QName("http://api.service.comm.esb.ymsino.com/", "RestoreSettingServicePort"), RestoreSettingService.class);
	}

}
