package com.ymsino.water.service.freesettle.waterMonthCost;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * WaterMonthCostServiceService service = new WaterMonthCostServiceService();
 * WaterMonthCostService portType = service.getWaterMonthCostServicePort();
 * portType.getById(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "WaterMonthCostServiceService", targetNamespace = "http://api.service.freesettle.esb.ymsino.com/", wsdlLocation = "http://127.0.0.1:8882/ws/waterMonthCostService?wsdl")
public class WaterMonthCostServiceService extends Service {

	private final static URL WATERMONTHCOSTSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.ymsino.water.service.freesettle.waterMonthCost.WaterMonthCostServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ymsino.water.service.freesettle.waterMonthCost.WaterMonthCostServiceService.class.getResource(".");
			url = new URL(baseUrl, "http://127.0.0.1:8882/ws/waterMonthCostService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8882/ws/waterMonthCostService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		WATERMONTHCOSTSERVICESERVICE_WSDL_LOCATION = url;
	}

	public WaterMonthCostServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public WaterMonthCostServiceService() {
		super(WATERMONTHCOSTSERVICESERVICE_WSDL_LOCATION, new QName("http://api.service.freesettle.esb.ymsino.com/", "WaterMonthCostServiceService"));
	}

	/**
	 * 
	 * @return returns WaterMonthCostService
	 */
	@WebEndpoint(name = "WaterMonthCostServicePort")
	public WaterMonthCostService getWaterMonthCostServicePort() {
		return super.getPort(new QName("http://api.service.freesettle.esb.ymsino.com/", "WaterMonthCostServicePort"), WaterMonthCostService.class);
	}

}
