package com.ymsino.water.service.manager.manager;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * ManagerServiceService service = new ManagerServiceService();
 * ManagerService portType = service.getManagerServicePort();
 * portType.login(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "ManagerServiceService", targetNamespace = "http://api.service.manager.esb.ymsino.com/", wsdlLocation = "http://127.0.0.1:8882/ws/managerService?wsdl")
public class ManagerServiceService extends Service {

	private final static URL MANAGERSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.ymsino.water.service.manager.manager.ManagerServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ymsino.water.service.manager.manager.ManagerServiceService.class.getResource(".");
			url = new URL(baseUrl, "http://127.0.0.1:8882/ws/managerService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8882/ws/managerService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		MANAGERSERVICESERVICE_WSDL_LOCATION = url;
	}

	public ManagerServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ManagerServiceService() {
		super(MANAGERSERVICESERVICE_WSDL_LOCATION, new QName("http://api.service.manager.esb.ymsino.com/", "ManagerServiceService"));
	}

	/**
	 * 
	 * @return returns ManagerService
	 */
	@WebEndpoint(name = "ManagerServicePort")
	public ManagerService getManagerServicePort() {
		return super.getPort(new QName("http://api.service.manager.esb.ymsino.com/", "ManagerServicePort"), ManagerService.class);
	}

}
