package com.ymsino.water.service.archives.waterCustomer;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * WaterCustomerServiceService service = new WaterCustomerServiceService();
 * WaterCustomerService portType = service.getWaterCustomerServicePort();
 * portType.save(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "WaterCustomerServiceService", targetNamespace = "http://api.service.archives.esb.ymsino.com/", wsdlLocation = "http://127.0.0.1:8882/ws/waterCustomerService?wsdl")
public class WaterCustomerServiceService extends Service {

	private final static URL WATERCUSTOMERSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.ymsino.water.service.archives.waterCustomer.WaterCustomerServiceService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ymsino.water.service.archives.waterCustomer.WaterCustomerServiceService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://127.0.0.1:8882/ws/waterCustomerService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8882/ws/waterCustomerService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		WATERCUSTOMERSERVICESERVICE_WSDL_LOCATION = url;
	}

	public WaterCustomerServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public WaterCustomerServiceService() {
		super(WATERCUSTOMERSERVICESERVICE_WSDL_LOCATION, new QName(
				"http://api.service.archives.esb.ymsino.com/",
				"WaterCustomerServiceService"));
	}

	/**
	 * 
	 * @return returns WaterCustomerService
	 */
	@WebEndpoint(name = "WaterCustomerServicePort")
	public WaterCustomerService getWaterCustomerServicePort() {
		return super.getPort(new QName(
				"http://api.service.archives.esb.ymsino.com/",
				"WaterCustomerServicePort"), WaterCustomerService.class);
	}

}
