package com.ymsino.water.service.archives.waterCustomer;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "WaterCustomerService", targetNamespace = "http://api.service.archives.esb.ymsino.com/")
public interface WaterCustomerService {

	/**
	 * 保存用水用户和供水点信息
	 * 
	 * @param waterCustomerSaveParam
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "save", targetNamespace = "http://api.service.archives.esb.ymsino.com/", className = "com.ymsino.water.service.archives.waterCustomer.Save")
	@ResponseWrapper(localName = "saveResponse", targetNamespace = "http://api.service.archives.esb.ymsino.com/", className = "com.ymsino.water.service.archives.waterCustomer.SaveResponse")
	public Boolean save(
			@WebParam(name = "waterCustomerSaveParam", targetNamespace = "") WaterCustomerSaveParam waterCustomerSaveParam);

	/**
	 * 根据id获取用水用户和供水点信息
	 * 
	 * @param customerId
	 * @return returns
	 *         com.ymsino.water.service.archives.waterCustomer.WaterCustomerReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getById", targetNamespace = "http://api.service.archives.esb.ymsino.com/", className = "com.ymsino.water.service.archives.waterCustomer.GetById")
	@ResponseWrapper(localName = "getByIdResponse", targetNamespace = "http://api.service.archives.esb.ymsino.com/", className = "com.ymsino.water.service.archives.waterCustomer.GetByIdResponse")
	public WaterCustomerReturn getById(
			@WebParam(name = "customerId", targetNamespace = "") String customerId);

	/**
	 * 根据查询参数获取用水用户和供水点信息总记录数
	 * 
	 * @param queryParam
	 * @return returns java.lang.Integer
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getCount", targetNamespace = "http://api.service.archives.esb.ymsino.com/", className = "com.ymsino.water.service.archives.waterCustomer.GetCount")
	@ResponseWrapper(localName = "getCountResponse", targetNamespace = "http://api.service.archives.esb.ymsino.com/", className = "com.ymsino.water.service.archives.waterCustomer.GetCountResponse")
	public Integer getCount(
			@WebParam(name = "queryParam", targetNamespace = "") QueryParam queryParam);

	/**
	 * 根据查询参数获取用水用户和供水点信息分页列表
	 * 
	 * @param queryParam
	 * @param startRow
	 * @param pageSize
	 * @return returns
	 *         java.util.List<com.ymsino.water.service.archives.waterCustomer
	 *         .WaterCustomerReturn>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getListpager", targetNamespace = "http://api.service.archives.esb.ymsino.com/", className = "com.ymsino.water.service.archives.waterCustomer.GetListpager")
	@ResponseWrapper(localName = "getListpagerResponse", targetNamespace = "http://api.service.archives.esb.ymsino.com/", className = "com.ymsino.water.service.archives.waterCustomer.GetListpagerResponse")
	public List<WaterCustomerReturn> getListpager(
			@WebParam(name = "queryParam", targetNamespace = "") QueryParam queryParam,
			@WebParam(name = "startRow", targetNamespace = "") Integer startRow,
			@WebParam(name = "pageSize", targetNamespace = "") Integer pageSize);

	/**
	 * 修改用水用户及供水点信息
	 * 
	 * @param waterCustomerModifyParam
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "modidy", targetNamespace = "http://api.service.archives.esb.ymsino.com/", className = "com.ymsino.water.service.archives.waterCustomer.Modidy")
	@ResponseWrapper(localName = "modidyResponse", targetNamespace = "http://api.service.archives.esb.ymsino.com/", className = "com.ymsino.water.service.archives.waterCustomer.ModidyResponse")
	public Boolean modidy(
			@WebParam(name = "waterCustomerModifyParam", targetNamespace = "") WaterCustomerModifyParam waterCustomerModifyParam);

}
