package com.ymsino.water.service.archives.contact;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * ContactServiceService service = new ContactServiceService();
 * ContactService portType = service.getContactServicePort();
 * portType.save(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "ContactServiceService", targetNamespace = "http://api.service.archives.esb.ymsino.com/", wsdlLocation = "http://127.0.0.1:8882/ws/contactService?wsdl")
public class ContactServiceService extends Service {

	private final static URL CONTACTSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.ymsino.water.service.archives.contact.ContactServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ymsino.water.service.archives.contact.ContactServiceService.class.getResource(".");
			url = new URL(baseUrl, "http://127.0.0.1:8882/ws/contactService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8882/ws/contactService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		CONTACTSERVICESERVICE_WSDL_LOCATION = url;
	}

	public ContactServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ContactServiceService() {
		super(CONTACTSERVICESERVICE_WSDL_LOCATION, new QName("http://api.service.archives.esb.ymsino.com/", "ContactServiceService"));
	}

	/**
	 * 
	 * @return returns ContactService
	 */
	@WebEndpoint(name = "ContactServicePort")
	public ContactService getContactServicePort() {
		return super.getPort(new QName("http://api.service.archives.esb.ymsino.com/", "ContactServicePort"), ContactService.class);
	}

}
