package com.ymsino.water.service.archives.contact;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * 
 */
@WebService(name = "ContactService", targetNamespace = "http://api.service.archives.esb.ymsino.com/")
public interface ContactService {

	/**
	 * 保存联系信息
	 * 
	 * @param contactSaveParam
	 * @return returns java.lang.Long
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "save", targetNamespace = "http://api.service.archives.esb.ymsino.com/", className = "com.ymsino.water.service.archives.contact.Save")
	@ResponseWrapper(localName = "saveResponse", targetNamespace = "http://api.service.archives.esb.ymsino.com/", className = "com.ymsino.water.service.archives.contact.SaveResponse")
	public Long save(@WebParam(name = "contactSaveParam", targetNamespace = "") ContactSaveParam contactSaveParam);

	/**
	 * 根据查询参数获取联系信息分页列表
	 * 
	 * @param queryParam
	 * @param startRow
	 * @param pageSize
	 * @return returns java.util.List<com.ymsino.water.service.archives.contact.ContactReturn>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getListpager", targetNamespace = "http://api.service.archives.esb.ymsino.com/", className = "com.ymsino.water.service.archives.contact.GetListpager")
	@ResponseWrapper(localName = "getListpagerResponse", targetNamespace = "http://api.service.archives.esb.ymsino.com/", className = "com.ymsino.water.service.archives.contact.GetListpagerResponse")
	public List<ContactReturn> getListpager(@WebParam(name = "queryParam", targetNamespace = "") QueryParam queryParam, @WebParam(name = "startRow", targetNamespace = "") Integer startRow, @WebParam(name = "pageSize", targetNamespace = "") Integer pageSize);

	/**
	 * 根据id获取联系信息
	 * 
	 * @param id
	 * @return returns com.ymsino.water.service.archives.contact.ContactReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getById", targetNamespace = "http://api.service.archives.esb.ymsino.com/", className = "com.ymsino.water.service.archives.contact.GetById")
	@ResponseWrapper(localName = "getByIdResponse", targetNamespace = "http://api.service.archives.esb.ymsino.com/", className = "com.ymsino.water.service.archives.contact.GetByIdResponse")
	public ContactReturn getById(@WebParam(name = "id", targetNamespace = "") Long id);

	/**
	 * 根据查询参数获取联系信息总记录数
	 * 
	 * @param queryParam
	 * @return returns java.lang.Integer
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getCount", targetNamespace = "http://api.service.archives.esb.ymsino.com/", className = "com.ymsino.water.service.archives.contact.GetCount")
	@ResponseWrapper(localName = "getCountResponse", targetNamespace = "http://api.service.archives.esb.ymsino.com/", className = "com.ymsino.water.service.archives.contact.GetCountResponse")
	public Integer getCount(@WebParam(name = "queryParam", targetNamespace = "") QueryParam queryParam);

	/**
	 * 修改联系信息
	 * 
	 * @param contactModifyParam
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "modify", targetNamespace = "http://api.service.archives.esb.ymsino.com/", className = "com.ymsino.water.service.archives.contact.Modify")
	@ResponseWrapper(localName = "modifyResponse", targetNamespace = "http://api.service.archives.esb.ymsino.com/", className = "com.ymsino.water.service.archives.contact.ModifyResponse")
	public Boolean modify(@WebParam(name = "contactModifyParam", targetNamespace = "") ContactModifyParam contactModifyParam);

	/**
	 * 删除联系信息
	 * 
	 * @param id
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "delete", targetNamespace = "http://api.service.archives.esb.ymsino.com/", className = "com.ymsino.water.service.archives.contact.Delete")
	@ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://api.service.archives.esb.ymsino.com/", className = "com.ymsino.water.service.archives.contact.DeleteResponse")
	public Boolean delete(@WebParam(name = "id", targetNamespace = "") Long id);

}
