package com.ymsino.water.service.comm.loadWm;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * 
 */
@WebFault(name = "InterruptedException", targetNamespace = "http://api.service.comm.esb.ymsino.com/")
public class InterruptedException_Exception extends Exception {

	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private InterruptedException faultInfo;

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 */
	public InterruptedException_Exception(String message, InterruptedException faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 * @param cause
	 */
	public InterruptedException_Exception(String message, InterruptedException faultInfo, Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean: com.ymsino.water.service.comm.loadWm.InterruptedException
	 */
	public InterruptedException getFaultInfo() {
		return faultInfo;
	}

}
