package com.ymsino.water.service.comm.loadWm;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * 
 */
@WebService(name = "LoadWmService", targetNamespace = "http://api.service.comm.esb.ymsino.com/")
public interface LoadWmService {

	/**
	 * 加载集中器水表参数
	 * 
	 * @param concHardwareId
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "loadWm", targetNamespace = "http://api.service.comm.esb.ymsino.com/", className = "com.ymsino.water.service.comm.loadWm.LoadWm")
	@ResponseWrapper(localName = "loadWmResponse", targetNamespace = "http://api.service.comm.esb.ymsino.com/", className = "com.ymsino.water.service.comm.loadWm.LoadWmResponse")
	public Boolean loadWm(@WebParam(name = "concHardwareId", targetNamespace = "") String concHardwareId);

	/**
	 * 读取集中器水表参数
	 * 
	 * @param wmSn
	 * @param count
	 * @param concHardwareId
	 * @return returns java.util.List<com.ymsino.water.service.comm.loadWm.MeterSnVo>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "readWaterMeterSn", targetNamespace = "http://api.service.comm.esb.ymsino.com/", className = "com.ymsino.water.service.comm.loadWm.ReadWaterMeterSn")
	@ResponseWrapper(localName = "readWaterMeterSnResponse", targetNamespace = "http://api.service.comm.esb.ymsino.com/", className = "com.ymsino.water.service.comm.loadWm.ReadWaterMeterSnResponse")
	public List<MeterSnVo> readWaterMeterSn(@WebParam(name = "concHardwareId", targetNamespace = "") String concHardwareId, @WebParam(name = "wmSn", targetNamespace = "") Integer wmSn, @WebParam(name = "count", targetNamespace = "") Integer count);

	/**
	 * 
	 * @throws InterruptedException_Exception
	 */
	@WebMethod
	@RequestWrapper(localName = "test", targetNamespace = "http://api.service.comm.esb.ymsino.com/", className = "com.ymsino.water.service.comm.loadWm.Test")
	@ResponseWrapper(localName = "testResponse", targetNamespace = "http://api.service.comm.esb.ymsino.com/", className = "com.ymsino.water.service.comm.loadWm.TestResponse")
	public void test() throws InterruptedException_Exception;

}
