package com.ymsino.water.service.archives.concentrator;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * ConcentratorServiceService service = new ConcentratorServiceService();
 * ConcentratorService portType = service.getConcentratorServicePort();
 * portType.save(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "ConcentratorServiceService", targetNamespace = "http://api.service.archives.esb.ymsino.com/", wsdlLocation = "http://127.0.0.1:8882/ws/concentratorService?wsdl")
public class ConcentratorServiceService extends Service {

	private final static URL CONCENTRATORSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.ymsino.water.service.archives.concentrator.ConcentratorServiceService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ymsino.water.service.archives.concentrator.ConcentratorServiceService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://127.0.0.1:8882/ws/concentratorService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8882/ws/concentratorService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		CONCENTRATORSERVICESERVICE_WSDL_LOCATION = url;
	}

	public ConcentratorServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ConcentratorServiceService() {
		super(CONCENTRATORSERVICESERVICE_WSDL_LOCATION, new QName(
				"http://api.service.archives.esb.ymsino.com/",
				"ConcentratorServiceService"));
	}

	/**
	 * 
	 * @return returns ConcentratorService
	 */
	@WebEndpoint(name = "ConcentratorServicePort")
	public ConcentratorService getConcentratorServicePort() {
		return super.getPort(new QName(
				"http://api.service.archives.esb.ymsino.com/",
				"ConcentratorServicePort"), ConcentratorService.class);
	}

}
