package com.ymsino.water.service.comm.readData;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * 
 */
@WebService(name = "ReadDataService", targetNamespace = "http://api.service.comm.esb.ymsino.com/")
public interface ReadDataService {

	/**
	 * 读日冻结数据
	 * 
	 * @param wmSn
	 * @param count
	 * @param concHardwareId
	 * @param dateStr
	 * @return returns java.util.List<com.ymsino.water.service.comm.readData.MeterDataVo>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "readDataByDate", targetNamespace = "http://api.service.comm.esb.ymsino.com/", className = "com.ymsino.water.service.comm.readData.ReadDataByDate")
	@ResponseWrapper(localName = "readDataByDateResponse", targetNamespace = "http://api.service.comm.esb.ymsino.com/", className = "com.ymsino.water.service.comm.readData.ReadDataByDateResponse")
	public List<MeterDataVo> readDataByDate(@WebParam(name = "concHardwareId", targetNamespace = "") String concHardwareId, @WebParam(name = "wmSn", targetNamespace = "") Integer wmSn, @WebParam(name = "count", targetNamespace = "") Integer count, @WebParam(name = "dateStr", targetNamespace = "") String dateStr);

}
