package com.ymsino.water.service.comm.readData;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * ReadDataServiceService service = new ReadDataServiceService();
 * ReadDataService portType = service.getReadDataServicePort();
 * portType.readDataByDate(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "ReadDataServiceService", targetNamespace = "http://api.service.comm.esb.ymsino.com/", wsdlLocation = "http://127.0.0.1:8882/ws/readDataService?wsdl")
public class ReadDataServiceService extends Service {

	private final static URL READDATASERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.ymsino.water.service.comm.readData.ReadDataServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ymsino.water.service.comm.readData.ReadDataServiceService.class.getResource(".");
			url = new URL(baseUrl, "http://127.0.0.1:8882/ws/readDataService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8882/ws/readDataService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		READDATASERVICESERVICE_WSDL_LOCATION = url;
	}

	public ReadDataServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ReadDataServiceService() {
		super(READDATASERVICESERVICE_WSDL_LOCATION, new QName("http://api.service.comm.esb.ymsino.com/", "ReadDataServiceService"));
	}

	/**
	 * 
	 * @return returns ReadDataService
	 */
	@WebEndpoint(name = "ReadDataServicePort")
	public ReadDataService getReadDataServicePort() {
		return super.getPort(new QName("http://api.service.comm.esb.ymsino.com/", "ReadDataServicePort"), ReadDataService.class);
	}

}
