package com.ymsino.water.service.manager.department;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * DepartmentServiceService service = new DepartmentServiceService();
 * DepartmentService portType = service.getDepartmentServicePort();
 * portType.save(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "DepartmentServiceService", targetNamespace = "http://api.service.manager.esb.ymsino.com/", wsdlLocation = "http://127.0.0.1:8882/ws/departmentService?wsdl")
public class DepartmentServiceService extends Service {

	private final static URL DEPARTMENTSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.ymsino.water.service.manager.department.DepartmentServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ymsino.water.service.manager.department.DepartmentServiceService.class.getResource(".");
			url = new URL(baseUrl, "http://127.0.0.1:8882/ws/departmentService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8882/ws/departmentService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		DEPARTMENTSERVICESERVICE_WSDL_LOCATION = url;
	}

	public DepartmentServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public DepartmentServiceService() {
		super(DEPARTMENTSERVICESERVICE_WSDL_LOCATION, new QName("http://api.service.manager.esb.ymsino.com/", "DepartmentServiceService"));
	}

	/**
	 * 
	 * @return returns DepartmentService
	 */
	@WebEndpoint(name = "DepartmentServicePort")
	public DepartmentService getDepartmentServicePort() {
		return super.getPort(new QName("http://api.service.manager.esb.ymsino.com/", "DepartmentServicePort"), DepartmentService.class);
	}

}
