package com.ymsino.water.service.comm.testMeterCode;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * TestMeterCodeServiceService service = new TestMeterCodeServiceService();
 * TestMeterCodeService portType = service.getTestMeterCodeServicePort();
 * portType.testMeterCode(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "TestMeterCodeServiceService", targetNamespace = "http://api.service.comm.esb.ymsino.com/", wsdlLocation = "http://127.0.0.1:8882/ws/testMeterCodeService?wsdl")
public class TestMeterCodeServiceService extends Service {

	private final static URL TESTMETERCODESERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.ymsino.water.service.comm.testMeterCode.TestMeterCodeServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ymsino.water.service.comm.testMeterCode.TestMeterCodeServiceService.class.getResource(".");
			url = new URL(baseUrl, "http://127.0.0.1:8882/ws/testMeterCodeService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8882/ws/testMeterCodeService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		TESTMETERCODESERVICESERVICE_WSDL_LOCATION = url;
	}

	public TestMeterCodeServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public TestMeterCodeServiceService() {
		super(TESTMETERCODESERVICESERVICE_WSDL_LOCATION, new QName("http://api.service.comm.esb.ymsino.com/", "TestMeterCodeServiceService"));
	}

	/**
	 * 
	 * @return returns TestMeterCodeService
	 */
	@WebEndpoint(name = "TestMeterCodeServicePort")
	public TestMeterCodeService getTestMeterCodeServicePort() {
		return super.getPort(new QName("http://api.service.comm.esb.ymsino.com/", "TestMeterCodeServicePort"), TestMeterCodeService.class);
	}

}
