package com.ymsino.water.service.comm.testMeterCode;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * 
 */
@WebService(name = "TestMeterCodeService", targetNamespace = "http://api.service.comm.esb.ymsino.com/")
public interface TestMeterCodeService {

	/**
	 * 集中器实时召测表码
	 * 
	 * @param waterMeterId
	 * @param concHardwareId
	 * @param waterMeterSn
	 * @return returns com.ymsino.water.service.comm.testMeterCode.MeterDataVo
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "testMeterCode", targetNamespace = "http://api.service.comm.esb.ymsino.com/", className = "com.ymsino.water.service.comm.testMeterCode.TestMeterCode")
	@ResponseWrapper(localName = "testMeterCodeResponse", targetNamespace = "http://api.service.comm.esb.ymsino.com/", className = "com.ymsino.water.service.comm.testMeterCode.TestMeterCodeResponse")
	public MeterDataVo testMeterCode(@WebParam(name = "concHardwareId", targetNamespace = "") String concHardwareId, @WebParam(name = "waterMeterId", targetNamespace = "") String waterMeterId, @WebParam(name = "waterMeterSn", targetNamespace = "") Integer waterMeterSn);

}
