package com.ymsino.water.service.comm.deleteData;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * DeleteDataServiceService service = new DeleteDataServiceService();
 * DeleteDataService portType = service.getDeleteDataServicePort();
 * portType.deleteData(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "DeleteDataServiceService", targetNamespace = "http://api.service.comm.esb.ymsino.com/", wsdlLocation = "http://127.0.0.1:8882/ws/deleteDataService?wsdl")
public class DeleteDataServiceService extends Service {

	private final static URL DELETEDATASERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.ymsino.water.service.comm.deleteData.DeleteDataServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ymsino.water.service.comm.deleteData.DeleteDataServiceService.class.getResource(".");
			url = new URL(baseUrl, "http://127.0.0.1:8882/ws/deleteDataService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8882/ws/deleteDataService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		DELETEDATASERVICESERVICE_WSDL_LOCATION = url;
	}

	public DeleteDataServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public DeleteDataServiceService() {
		super(DELETEDATASERVICESERVICE_WSDL_LOCATION, new QName("http://api.service.comm.esb.ymsino.com/", "DeleteDataServiceService"));
	}

	/**
	 * 
	 * @return returns DeleteDataService
	 */
	@WebEndpoint(name = "DeleteDataServicePort")
	public DeleteDataService getDeleteDataServicePort() {
		return super.getPort(new QName("http://api.service.comm.esb.ymsino.com/", "DeleteDataServicePort"), DeleteDataService.class);
	}

}
