package com.ymsino.water.service.data.freezeData;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * FreezeDataServiceService service = new FreezeDataServiceService();
 * FreezeDataService portType = service.getFreezeDataServicePort();
 * portType.getCount(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "FreezeDataServiceService", targetNamespace = "http://api.service.data.esb.ymsino.com/", wsdlLocation = "http://127.0.0.1:8882/ws/freezeDataService?wsdl")
public class FreezeDataServiceService extends Service {

	private final static URL FREEZEDATASERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.ymsino.water.service.data.freezeData.FreezeDataServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ymsino.water.service.data.freezeData.FreezeDataServiceService.class.getResource(".");
			url = new URL(baseUrl, "http://127.0.0.1:8882/ws/freezeDataService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8882/ws/freezeDataService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		FREEZEDATASERVICESERVICE_WSDL_LOCATION = url;
	}

	public FreezeDataServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public FreezeDataServiceService() {
		super(FREEZEDATASERVICESERVICE_WSDL_LOCATION, new QName("http://api.service.data.esb.ymsino.com/", "FreezeDataServiceService"));
	}

	/**
	 * 
	 * @return returns FreezeDataService
	 */
	@WebEndpoint(name = "FreezeDataServicePort")
	public FreezeDataService getFreezeDataServicePort() {
		return super.getPort(new QName("http://api.service.data.esb.ymsino.com/", "FreezeDataServicePort"), FreezeDataService.class);
	}

}
