package com.ymsino.water.service.freesettle.waterDayCost;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * 
 */
@WebService(name = "WaterDayCostService", targetNamespace = "http://api.service.freesettle.esb.ymsino.com/")
public interface WaterDayCostService {

	/**
	 * 根据id获取水表日费用对象
	 * 
	 * @param id
	 * @return returns com.ymsino.water.service.freesettle.waterDayCost.WaterDayCostReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getById", targetNamespace = "http://api.service.freesettle.esb.ymsino.com/", className = "com.ymsino.water.service.freesettle.waterDayCost.GetById")
	@ResponseWrapper(localName = "getByIdResponse", targetNamespace = "http://api.service.freesettle.esb.ymsino.com/", className = "com.ymsino.water.service.freesettle.waterDayCost.GetByIdResponse")
	public WaterDayCostReturn getById(@WebParam(name = "id", targetNamespace = "") Long id);

	/**
	 * 结算本月水费
	 * 
	 * @param dayCostId
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "settleCost", targetNamespace = "http://api.service.freesettle.esb.ymsino.com/", className = "com.ymsino.water.service.freesettle.waterDayCost.SettleCost")
	@ResponseWrapper(localName = "settleCostResponse", targetNamespace = "http://api.service.freesettle.esb.ymsino.com/", className = "com.ymsino.water.service.freesettle.waterDayCost.SettleCostResponse")
	public Boolean settleCost(@WebParam(name = "dayCostId", targetNamespace = "") Long dayCostId);

	/**
	 * 根据查询参数获取水表日费用分页列表
	 * 
	 * @param queryParam
	 * @param startRow
	 * @param pageSize
	 * @return returns java.util.List<com.ymsino.water.service.freesettle.waterDayCost.WaterDayCostReturn>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getListpager", targetNamespace = "http://api.service.freesettle.esb.ymsino.com/", className = "com.ymsino.water.service.freesettle.waterDayCost.GetListpager")
	@ResponseWrapper(localName = "getListpagerResponse", targetNamespace = "http://api.service.freesettle.esb.ymsino.com/", className = "com.ymsino.water.service.freesettle.waterDayCost.GetListpagerResponse")
	public List<WaterDayCostReturn> getListpager(@WebParam(name = "queryParam", targetNamespace = "") QueryParam queryParam, @WebParam(name = "startRow", targetNamespace = "") Integer startRow, @WebParam(name = "pageSize", targetNamespace = "") Integer pageSize);

	/**
	 * 根据查询参数获取水表日费用总记录数
	 * 
	 * @param queryParam
	 * @return returns java.lang.Integer
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getCount", targetNamespace = "http://api.service.freesettle.esb.ymsino.com/", className = "com.ymsino.water.service.freesettle.waterDayCost.GetCount")
	@ResponseWrapper(localName = "getCountResponse", targetNamespace = "http://api.service.freesettle.esb.ymsino.com/", className = "com.ymsino.water.service.freesettle.waterDayCost.GetCountResponse")
	public Integer getCount(@WebParam(name = "queryParam", targetNamespace = "") QueryParam queryParam);

}
