package com.ymsino.water.service.data.testDynamicData;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * TestDynamicDataServiceService service = new TestDynamicDataServiceService();
 * TestDynamicDataService portType = service.getTestDynamicDataServicePort();
 * portType.getCount(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "TestDynamicDataServiceService", targetNamespace = "http://api.service.data.esb.ymsino.com/", wsdlLocation = "http://127.0.0.1:8882/ws/testDynamicDataService?wsdl")
public class TestDynamicDataServiceService extends Service {

	private final static URL TESTDYNAMICDATASERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.ymsino.water.service.data.testDynamicData.TestDynamicDataServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ymsino.water.service.data.testDynamicData.TestDynamicDataServiceService.class.getResource(".");
			url = new URL(baseUrl, "http://127.0.0.1:8882/ws/testDynamicDataService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8882/ws/testDynamicDataService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		TESTDYNAMICDATASERVICESERVICE_WSDL_LOCATION = url;
	}

	public TestDynamicDataServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public TestDynamicDataServiceService() {
		super(TESTDYNAMICDATASERVICESERVICE_WSDL_LOCATION, new QName("http://api.service.data.esb.ymsino.com/", "TestDynamicDataServiceService"));
	}

	/**
	 * 
	 * @return returns TestDynamicDataService
	 */
	@WebEndpoint(name = "TestDynamicDataServicePort")
	public TestDynamicDataService getTestDynamicDataServicePort() {
		return super.getPort(new QName("http://api.service.data.esb.ymsino.com/", "TestDynamicDataServicePort"), TestDynamicDataService.class);
	}

}
