package com.ymsino.water.service.archives.user;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * UserServiceService service = new UserServiceService();
 * UserService portType = service.getUserServicePort();
 * portType.getByUserId(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "UserServiceService", targetNamespace = "http://api.service.archives.esb.ymsino.com/", wsdlLocation = "http://127.0.0.1:8882/ws/userService?wsdl")
public class UserServiceService extends Service {

	private final static URL USERSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.ymsino.water.service.archives.user.UserServiceService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ymsino.water.service.archives.user.UserServiceService.class
					.getResource(".");
			url = new URL(baseUrl, "http://127.0.0.1:8882/ws/userService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8882/ws/userService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		USERSERVICESERVICE_WSDL_LOCATION = url;
	}

	public UserServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public UserServiceService() {
		super(USERSERVICESERVICE_WSDL_LOCATION, new QName(
				"http://api.service.archives.esb.ymsino.com/",
				"UserServiceService"));
	}

	/**
	 * 
	 * @return returns UserService
	 */
	@WebEndpoint(name = "UserServicePort")
	public UserService getUserServicePort() {
		return super.getPort(new QName(
				"http://api.service.archives.esb.ymsino.com/",
				"UserServicePort"), UserService.class);
	}

}
