package com.ymsino.water.service.freesettle.userWallet;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * 
 */
@WebService(name = "UserWalletService", targetNamespace = "http://api.service.freesettle.esb.ymsino.com/")
public interface UserWalletService {

	/**
	 * 根据用户id获取用户钱包
	 * 
	 * @param uid
	 * @return returns com.ymsino.water.service.freesettle.userWallet.UserWalletReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getByUid", targetNamespace = "http://api.service.freesettle.esb.ymsino.com/", className = "com.ymsino.water.service.freesettle.userWallet.GetByUid")
	@ResponseWrapper(localName = "getByUidResponse", targetNamespace = "http://api.service.freesettle.esb.ymsino.com/", className = "com.ymsino.water.service.freesettle.userWallet.GetByUidResponse")
	public UserWalletReturn getByUid(@WebParam(name = "uid", targetNamespace = "") Long uid);

	/**
	 * 充值
	 * 
	 * @param uid
	 * @param price
	 * @param sysRemark
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "recharge", targetNamespace = "http://api.service.freesettle.esb.ymsino.com/", className = "com.ymsino.water.service.freesettle.userWallet.Recharge")
	@ResponseWrapper(localName = "rechargeResponse", targetNamespace = "http://api.service.freesettle.esb.ymsino.com/", className = "com.ymsino.water.service.freesettle.userWallet.RechargeResponse")
	public Boolean recharge(@WebParam(name = "uid", targetNamespace = "") Long uid, @WebParam(name = "price", targetNamespace = "") Long price, @WebParam(name = "sysRemark", targetNamespace = "") String sysRemark);

	/**
	 * 扣费
	 * 
	 * @param uid
	 * @param price
	 * @param sysRemark
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "deduction", targetNamespace = "http://api.service.freesettle.esb.ymsino.com/", className = "com.ymsino.water.service.freesettle.userWallet.Deduction")
	@ResponseWrapper(localName = "deductionResponse", targetNamespace = "http://api.service.freesettle.esb.ymsino.com/", className = "com.ymsino.water.service.freesettle.userWallet.DeductionResponse")
	public Boolean deduction(@WebParam(name = "uid", targetNamespace = "") Long uid, @WebParam(name = "price", targetNamespace = "") Long price, @WebParam(name = "sysRemark", targetNamespace = "") String sysRemark);

}
