package com.ymsino.water.service.comm.conClock;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * 
 */
@WebService(name = "ConClockService", targetNamespace = "http://api.service.comm.esb.ymsino.com/")
public interface ConClockService {

	/**
	 * 读取集中器时钟
	 * 
	 * @param concHardwareId
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "readClock", targetNamespace = "http://api.service.comm.esb.ymsino.com/", className = "com.ymsino.water.service.comm.conClock.ReadClock")
	@ResponseWrapper(localName = "readClockResponse", targetNamespace = "http://api.service.comm.esb.ymsino.com/", className = "com.ymsino.water.service.comm.conClock.ReadClockResponse")
	public String readClock(@WebParam(name = "concHardwareId", targetNamespace = "") String concHardwareId);

	/**
	 * 设置集中器时钟
	 * 
	 * @param concHardwareId
	 * @param dateStr
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "setupClock", targetNamespace = "http://api.service.comm.esb.ymsino.com/", className = "com.ymsino.water.service.comm.conClock.SetupClock")
	@ResponseWrapper(localName = "setupClockResponse", targetNamespace = "http://api.service.comm.esb.ymsino.com/", className = "com.ymsino.water.service.comm.conClock.SetupClockResponse")
	public String setupClock(@WebParam(name = "concHardwareId", targetNamespace = "") String concHardwareId, @WebParam(name = "dateStr", targetNamespace = "") String dateStr);

}
