package com.ymsino.water.service.comm.conClock;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * ConClockServiceService service = new ConClockServiceService();
 * ConClockService portType = service.getConClockServicePort();
 * portType.readClock(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "ConClockServiceService", targetNamespace = "http://api.service.comm.esb.ymsino.com/", wsdlLocation = "http://127.0.0.1:8882/ws/conClockService?wsdl")
public class ConClockServiceService extends Service {

	private final static URL CONCLOCKSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.ymsino.water.service.comm.conClock.ConClockServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ymsino.water.service.comm.conClock.ConClockServiceService.class.getResource(".");
			url = new URL(baseUrl, "http://127.0.0.1:8882/ws/conClockService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8882/ws/conClockService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		CONCLOCKSERVICESERVICE_WSDL_LOCATION = url;
	}

	public ConClockServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ConClockServiceService() {
		super(CONCLOCKSERVICESERVICE_WSDL_LOCATION, new QName("http://api.service.comm.esb.ymsino.com/", "ConClockServiceService"));
	}

	/**
	 * 
	 * @return returns ConClockService
	 */
	@WebEndpoint(name = "ConClockServicePort")
	public ConClockService getConClockServicePort() {
		return super.getPort(new QName("http://api.service.comm.esb.ymsino.com/", "ConClockServicePort"), ConClockService.class);
	}

}
