package com.ymsino.water.service.comm.testData;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * 
 */
@WebService(name = "TestDataService", targetNamespace = "http://api.service.comm.esb.ymsino.com/")
public interface TestDataService {

	/**
	 * 集中器召测本机动态数据
	 * 
	 * @param waterMeterId
	 * @param concHardwareId
	 * @param waterMeterSn
	 * @return returns com.ymsino.water.service.comm.testData.MeterDataVo
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "testData", targetNamespace = "http://api.service.comm.esb.ymsino.com/", className = "com.ymsino.water.service.comm.testData.TestData")
	@ResponseWrapper(localName = "testDataResponse", targetNamespace = "http://api.service.comm.esb.ymsino.com/", className = "com.ymsino.water.service.comm.testData.TestDataResponse")
	public MeterDataVo testData(@WebParam(name = "concHardwareId", targetNamespace = "") String concHardwareId, @WebParam(name = "waterMeterId", targetNamespace = "") String waterMeterId, @WebParam(name = "waterMeterSn", targetNamespace = "") Integer waterMeterSn);

}
