package com.ymsino.water.service.comm.deleteSettings;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * 
 */
@WebService(name = "DeleteSettingsService", targetNamespace = "http://api.service.comm.esb.ymsino.com/")
public interface DeleteSettingsService {

	/**
	 * 删除集中器配置信息
	 * 
	 * @param concHardwareId
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "deleteSettings", targetNamespace = "http://api.service.comm.esb.ymsino.com/", className = "com.ymsino.water.service.comm.deleteSettings.DeleteSettings")
	@ResponseWrapper(localName = "deleteSettingsResponse", targetNamespace = "http://api.service.comm.esb.ymsino.com/", className = "com.ymsino.water.service.comm.deleteSettings.DeleteSettingsResponse")
	public String deleteSettings(@WebParam(name = "concHardwareId", targetNamespace = "") String concHardwareId);

}
