package com.ymsino.water.service.freesettle.userWalletLog;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * UserWalletLogServiceService service = new UserWalletLogServiceService();
 * UserWalletLogService portType = service.getUserWalletLogServicePort();
 * portType.getListpager(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "UserWalletLogServiceService", targetNamespace = "http://api.service.freesettle.esb.ymsino.com/", wsdlLocation = "http://127.0.0.1:8882/ws/userWalletLogService?wsdl")
public class UserWalletLogServiceService extends Service {

	private final static URL USERWALLETLOGSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.ymsino.water.service.freesettle.userWalletLog.UserWalletLogServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ymsino.water.service.freesettle.userWalletLog.UserWalletLogServiceService.class.getResource(".");
			url = new URL(baseUrl, "http://127.0.0.1:8882/ws/userWalletLogService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8882/ws/userWalletLogService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		USERWALLETLOGSERVICESERVICE_WSDL_LOCATION = url;
	}

	public UserWalletLogServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public UserWalletLogServiceService() {
		super(USERWALLETLOGSERVICESERVICE_WSDL_LOCATION, new QName("http://api.service.freesettle.esb.ymsino.com/", "UserWalletLogServiceService"));
	}

	/**
	 * 
	 * @return returns UserWalletLogService
	 */
	@WebEndpoint(name = "UserWalletLogServicePort")
	public UserWalletLogService getUserWalletLogServicePort() {
		return super.getPort(new QName("http://api.service.freesettle.esb.ymsino.com/", "UserWalletLogServicePort"), UserWalletLogService.class);
	}

}
