package com.ymsino.water.service.freesettle.userWalletLog;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * 
 */
@WebService(name = "UserWalletLogService", targetNamespace = "http://api.service.freesettle.esb.ymsino.com/")
public interface UserWalletLogService {

	/**
	 * 根据查询参数获取用户余额日志分页列表
	 * 
	 * @param queryParam
	 * @param startRow
	 * @param pageSize
	 * @return returns java.util.List<com.ymsino.water.service.freesettle.userWalletLog.UserWalletLogReturn>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getListpager", targetNamespace = "http://api.service.freesettle.esb.ymsino.com/", className = "com.ymsino.water.service.freesettle.userWalletLog.GetListpager")
	@ResponseWrapper(localName = "getListpagerResponse", targetNamespace = "http://api.service.freesettle.esb.ymsino.com/", className = "com.ymsino.water.service.freesettle.userWalletLog.GetListpagerResponse")
	public List<UserWalletLogReturn> getListpager(@WebParam(name = "queryParam", targetNamespace = "") QueryParam queryParam, @WebParam(name = "startRow", targetNamespace = "") Integer startRow, @WebParam(name = "pageSize", targetNamespace = "") Integer pageSize);

	/**
	 * 根据查询参数获取用户余额日志总记录数
	 * 
	 * @param queryParam
	 * @return returns java.lang.Integer
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getCount", targetNamespace = "http://api.service.freesettle.esb.ymsino.com/", className = "com.ymsino.water.service.freesettle.userWalletLog.GetCount")
	@ResponseWrapper(localName = "getCountResponse", targetNamespace = "http://api.service.freesettle.esb.ymsino.com/", className = "com.ymsino.water.service.freesettle.userWalletLog.GetCountResponse")
	public Integer getCount(@WebParam(name = "queryParam", targetNamespace = "") QueryParam queryParam);

}
