package com.ymsino.water.service.manager.priceTemplate;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * 
 */
@WebService(name = "PriceTemplateService", targetNamespace = "http://api.service.manager.esb.ymsino.com/")
public interface PriceTemplateService {

	/**
	 * 根据查询参数获取价目分页列表
	 * 
	 * @param queryParam
	 * @param startRow
	 * @param pageSize
	 * @return returns java.util.List<com.ymsino.water.service.manager.priceTemplate.PriceTemplateReturn>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getListpager", targetNamespace = "http://api.service.manager.esb.ymsino.com/", className = "com.ymsino.water.service.manager.priceTemplate.GetListpager")
	@ResponseWrapper(localName = "getListpagerResponse", targetNamespace = "http://api.service.manager.esb.ymsino.com/", className = "com.ymsino.water.service.manager.priceTemplate.GetListpagerResponse")
	public List<PriceTemplateReturn> getListpager(@WebParam(name = "queryParam", targetNamespace = "") QueryParam queryParam, @WebParam(name = "startRow", targetNamespace = "") Integer startRow, @WebParam(name = "pageSize", targetNamespace = "") Integer pageSize);

	/**
	 * 修改价目
	 * 
	 * @param priceTemplateModifyParam
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "modify", targetNamespace = "http://api.service.manager.esb.ymsino.com/", className = "com.ymsino.water.service.manager.priceTemplate.Modify")
	@ResponseWrapper(localName = "modifyResponse", targetNamespace = "http://api.service.manager.esb.ymsino.com/", className = "com.ymsino.water.service.manager.priceTemplate.ModifyResponse")
	public Boolean modify(@WebParam(name = "priceTemplateModifyParam", targetNamespace = "") PriceTemplateModifyParam priceTemplateModifyParam);

	/**
	 * 保存价目
	 * 
	 * @param priceTemplateSaveParam
	 * @return returns java.lang.Long
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "save", targetNamespace = "http://api.service.manager.esb.ymsino.com/", className = "com.ymsino.water.service.manager.priceTemplate.Save")
	@ResponseWrapper(localName = "saveResponse", targetNamespace = "http://api.service.manager.esb.ymsino.com/", className = "com.ymsino.water.service.manager.priceTemplate.SaveResponse")
	public Long save(@WebParam(name = "priceTemplateSaveParam", targetNamespace = "") PriceTemplateSaveParam priceTemplateSaveParam);

	/**
	 * 根据id获取价目
	 * 
	 * @param id
	 * @return returns com.ymsino.water.service.manager.priceTemplate.PriceTemplateReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getById", targetNamespace = "http://api.service.manager.esb.ymsino.com/", className = "com.ymsino.water.service.manager.priceTemplate.GetById")
	@ResponseWrapper(localName = "getByIdResponse", targetNamespace = "http://api.service.manager.esb.ymsino.com/", className = "com.ymsino.water.service.manager.priceTemplate.GetByIdResponse")
	public PriceTemplateReturn getById(@WebParam(name = "id", targetNamespace = "") Long id);

	/**
	 * 根据查询参数获取价目总记录数
	 * 
	 * @param queryParam
	 * @return returns java.lang.Integer
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getCount", targetNamespace = "http://api.service.manager.esb.ymsino.com/", className = "com.ymsino.water.service.manager.priceTemplate.GetCount")
	@ResponseWrapper(localName = "getCountResponse", targetNamespace = "http://api.service.manager.esb.ymsino.com/", className = "com.ymsino.water.service.manager.priceTemplate.GetCountResponse")
	public Integer getCount(@WebParam(name = "queryParam", targetNamespace = "") QueryParam queryParam);

}
