package com.ymsino.water.service.archives.busiAddress;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * BusiAddressServiceService service = new BusiAddressServiceService();
 * BusiAddressService portType = service.getBusiAddressServicePort();
 * portType.save(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "BusiAddressServiceService", targetNamespace = "http://api.service.archives.esb.ymsino.com/", wsdlLocation = "http://127.0.0.1:8882/ws/busiAddressService?wsdl")
public class BusiAddressServiceService extends Service {

	private final static URL BUSIADDRESSSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.ymsino.water.service.archives.busiAddress.BusiAddressServiceService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ymsino.water.service.archives.busiAddress.BusiAddressServiceService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://127.0.0.1:8882/ws/busiAddressService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8882/ws/busiAddressService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		BUSIADDRESSSERVICESERVICE_WSDL_LOCATION = url;
	}

	public BusiAddressServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public BusiAddressServiceService() {
		super(BUSIADDRESSSERVICESERVICE_WSDL_LOCATION, new QName(
				"http://api.service.archives.esb.ymsino.com/",
				"BusiAddressServiceService"));
	}

	/**
	 * 
	 * @return returns BusiAddressService
	 */
	@WebEndpoint(name = "BusiAddressServicePort")
	public BusiAddressService getBusiAddressServicePort() {
		return super.getPort(new QName(
				"http://api.service.archives.esb.ymsino.com/",
				"BusiAddressServicePort"), BusiAddressService.class);
	}

}
